branch-defaults:
  main:
    environment: x22114327PriyaEmployeeApp-env
  master:
    environment: x22114327PriyaEmployeeApp-env
    group_suffix: null
environment-defaults:
  x22114327PriyaEmployeeApp-env:
    branch: null
    repository: null
global:
  application_name: x22114327_Priya_EmployeeApp
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
